import Foundation

final class DocGenerator {
    private let repoURL: URL
    private let scan: ScanResult
    private let fm = FileManager.default

    init(repoURL: URL, scanResult: ScanResult) {
        self.repoURL = repoURL
        self.scan = scanResult
    }

    // MARK: - Overview
    func generateOverview() throws {
        let overviewURL = repoURL.appendingPathComponent("PROJECT_OVERVIEW.md")

        guard !fm.fileExists(atPath: overviewURL.path) else {
            print("Warning: PROJECT_OVERVIEW.md already exists. Skipping.")
            return
        }

        let content = """
        # Project Overview

        ## Description
        This project was documented using RepoDoc CLI.

        ## Tech Stack
        \(scan.detectedStacks.map { "- \($0)" }.joined(separator: "\n"))

        ## Key Files
        \(scan.keyFilesFound.map { "- \($0)" }.joined(separator: "\n"))

        ## CI/CD
        \(scan.ciSignals.joined(separator: ", "))

        ---
        Generated by RepoDoc CLI
        """

        try content.write(to: overviewURL, atomically: true, encoding: .utf8)
    }

    // MARK: - Structure
    func generateStructure(maxDepth: Int) throws {
        let docsURL = repoURL.appendingPathComponent("docs")

        if !fm.fileExists(atPath: docsURL.path) {
            try fm.createDirectory(at: docsURL, withIntermediateDirectories: true)
        }

        let structureURL = docsURL.appendingPathComponent("STRUCTURE.md")

        guard !fm.fileExists(atPath: structureURL.path) else {
            print("Warning: STRUCTURE.md already exists. Skipping.")
            return
        }

        let tree = DirectoryTreeBuilder.buildTree(
            root: repoURL,
            maxDepth: maxDepth
        )

        let content = """
        # Project Structure

        ```
        \(tree)
        ```

        ---
        Generated by RepoDoc CLI
        """

        try content.write(to: structureURL, atomically: true, encoding: .utf8)
    }
}
