import Foundation

final class ReadmeGenerator {
    private let repoURL: URL
    private let scan: ScanResult
    private let fm = FileManager.default

    init(repoURL: URL, scanResult: ScanResult) {
        self.repoURL = repoURL
        self.scan = scanResult
    }

    func generate(tree: String, force: Bool) throws {
        let readmeURL = repoURL.appendingPathComponent("README.md")

        if fm.fileExists(atPath: readmeURL.path), !force {
            print("README.md already exists. Skipping. Use --force to overwrite.")
            return
        }

        // Nombre del proyecto (mejor que lastPathComponent en algunos casos)
        let projectName = repoURL.lastPathComponent.isEmpty ? "Project" : repoURL.lastPathComponent

        // Stack con enlaces
        let techLines: [String] = scan.detectedStacks.map { stack in
            if let tech = TechStackLinker.link(for: stack) {
                return "- [\(tech.display)](\(tech.url))  \n  _Detected as: \(stack)_"
            } else {
                return "- \(stack)"
            }
        }

        // Instrucciones básicas según stack detectado (heurístico simple)
        let howToRun = buildHowToRunSection()

        let originRemote = AuthorDetector.detectRepoOrigin(repoURL: repoURL)
        let authorName = originRemote.flatMap { AuthorDetector.extractOwner(from: $0) } ?? "TODO"

        let authorBlock: String = """
        ## Author
        - \(authorName)
        """



        // Licencia si existe
        let licenseLine: String = {
            if scan.keyFilesFound.contains("LICENSE") || scan.keyFilesFound.contains("LICENSE.md") {
                return "This repository includes a LICENSE file."
            }
            return "TODO (add a LICENSE file if applicable)"
        }()

        // CI signals (y link si aplica)
        let ciLines: [String] = scan.ciSignals.map { ci in
            if let tech = TechStackLinker.link(for: ci) {
                return "- [\(tech.display)](\(tech.url))"
            }
            return "- \(ci)"
        }

        let content = """
        # \(projectName)

        ## Description
        This README was generated by **RepoDoc CLI** using repository signals (stack detection, key files, CI, and structure).
        Edit this section to describe the purpose, features, and context of the project.

        ## Tech Stack
        \(techLines.isEmpty ? "- Unknown" : techLines.joined(separator: "\n"))

        ## Key Files
        \(formatList(scan.keyFilesFound, empty: "No key files detected."))

        ## CI / Automation
        \(ciLines.isEmpty ? "- None detected" : ciLines.joined(separator: "\n"))

        ## Project Structure
        ```
        \(tree.isEmpty ? "(empty)" : tree)
        ```

        ## How to Run
        \(howToRun)

        \(authorBlock)

        ## License
        \(licenseLine)

        ---
        _Generated by RepoDoc CLI_
        """

        try content.write(to: readmeURL, atomically: true, encoding: .utf8)
    }

    private func formatList(_ items: [String], empty: String) -> String {
        guard !items.isEmpty else { return "- \(empty)" }
        return items.map { "- \($0)" }.joined(separator: "\n")
    }

    private func buildHowToRunSection() -> String {
        // Swift SPM
        if scan.detectedStacks.contains(where: { $0.lowercased().contains("swift") }) {
            return """
            ```bash
            swift build
            swift run RepoDoc --help
            ```
            """
        }

        // Node
        if scan.detectedStacks.contains(where: { $0.lowercased().contains("node") }) {
            return """
            ```bash
            npm install
            npm run dev
            ```
            """
        }

        // Python
        if scan.detectedStacks.contains(where: { $0.lowercased().contains("python") }) {
            return """
            ```bash
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            ```
            """
        }

        return "TODO (add run instructions)"
    }
}
